@echo off
setlocal
cd /d "%~dp0"

rem One-time presentation profile. These values apply only to this process.
set "EXPERTSEARCH_DEMO_MODE=true"
set "EXPERTSEARCH_DEMO_FAST_MODE=true"
set "EXPERTSEARCH_DEMO_TOTAL_EXPERTS=10"
set "SUBDOMAIN_TARGET_EXPERTS=10"
set "RESEARCHER_TARGET_EXPERTS=10"
set "RESEARCHER_CHUNK_SIZE=10"
set "RESEARCHER_MAX_BATCH_ATTEMPTS=1"
set "SUBDOMAIN_TIER_RECOVERY_ATTEMPTS=0"
set "SUBDOMAIN_FINAL_TOPUP_ATTEMPTS=0"
set "LLM_MODEL=gpt-4.1"
set "LLM_TIMEOUT_SECONDS=75"
set "LLM_RETRY_ATTEMPTS=1"
set "LLM_CLIENT_MAX_RETRIES=0"
set "TAVILY_SEARCH_DEPTH=ultra-fast"
set "TAVILY_MAX_RESULTS=2"
set "OPENALEX_TIMEOUT_SECONDS=5"
set "OPENALEX_MAX_RETRIES=1"
set "OPENALEX_RETRY_BACKOFF_SECONDS=1"
set "OPENALEX_MIN_INTERVAL_SECONDS=0.15"
set "OPENALEX_CONTEXT_AUTHORS=3"
set "OPENALEX_CONTEXT_WORKS=2"
set "RESEARCHER_OPENALEX_CONTEXT_CHARS=2200"
set "RESEARCHER_TAVILY_CONTEXT_CHARS=1600"
set "RESEARCHER_TOTAL_EVIDENCE_CHARS=5000"
set "ENABLE_SEMANTIC_SCHOLAR_CONTEXT=false"
set "SEMANTIC_SCHOLAR_MAX_ROWS=0"
set "EXPERT_ENRICHMENT_MAX_OPENALEX_RETRY_ROWS=0"
set "EXPERT_ENRICHMENT_MAX_COLLAB_ROWS=0"
set "EXPERT_ENRICHMENT_MAX_S2_RETRY_ROWS=0"
set "FINAL_ENRICHMENT_MAX_S2_ROWS=0"
set "EXPERT_ENRICHMENT_MAX_HOMEPAGE_ROWS=1"
set "EXPERT_ENRICHMENT_HOMEPAGE_TIMEOUT_SECONDS=5"
set "EXPERT_ENRICHMENT_MAX_HOMEPAGE_RETRY_ROWS=0"
set "EXPERT_ENRICHMENT_MAX_TAVILY_ROWS=1"
set "EXPERT_ENRICHMENT_TAVILY_RESULTS=2"
set "EXPERT_ENRICHMENT_TAVILY_SEARCH_DEPTH=ultra-fast"
set "EXPERT_ENRICHMENT_COMPACT_TAVILY=true"
set "SURVIVAL_VERIFICATION_MAX_ROWS=0"
set "SURVIVAL_VERIFICATION_TAVILY_RESULTS=0"
set "OPENCLI_HOMEPAGE_MAX_CALLS_PER_PROCESS=0"
set "DELIVERY_ENABLE_LLM_TRANSLATION=false"

echo Starting ExpertSearch one-time demo profile...
echo Demo output target: 10 experts from one sub-domain in about 3 minutes.
echo The normal .env file and main branch are not modified.
echo.

call "%~dp0start_streamlit_logged.cmd"

endlocal
